// App constants
import type { Recipe, RecipeCategory, CuisineType, DietType } from '../types/recipe';

export const APP_NAME = 'FLAVOUR VAULT';
export const APP_TAGLINE = 'Your Recipes, Beautifully Organized';
export const APP_DESCRIPTION = 'Save, search, and discover recipes with a premium culinary experience.';

export const DB_NAME = 'flavour-vault-db';
export const DB_VERSION = 1;
export const RECIPE_STORE = 'recipes';

export const MAX_IMAGE_SIZE = 1024 * 1024; // 1MB after compression
export const IMAGE_QUALITY = 0.7;
export const MAX_IMAGES_PER_RECIPE = 10;
export const THUMBNAIL_SIZE = 400;

export const STATS = [
  { label: 'Recipes Ready', value: '500+', icon: 'book-open' },
  { label: 'Easy to Use', value: '100%', icon: 'sparkles' },
  { label: 'Completely Free', value: 'Free', icon: 'heart' },
  { label: 'Categories', value: '7+', icon: 'grid-3x3' },
];

export const FEATURES = [
  {
    title: 'Save Unlimited Recipes',
    description: 'Store all your favorite recipes locally. No limits, no subscriptions — your kitchen, your rules.',
    icon: 'book-open',
  },
  {
    title: 'Upload Beautiful Photos',
    description: 'Capture every step of your cooking journey with multiple photos per recipe.',
    icon: 'camera',
  },
  {
    title: 'Smart Ingredient Search',
    description: 'Search by what you have. Find recipes based on ingredients in your kitchen.',
    icon: 'search',
  },
  {
    title: 'Favorite & Organize',
    description: 'Heart your best recipes and organize them by category, cuisine, and diet type.',
    icon: 'heart',
  },
];

export const HOW_IT_WORKS = [
  {
    step: 1,
    title: 'Add Your Recipe',
    description: 'Enter your recipe details — ingredients, steps, cooking time, and more.',
    icon: 'plus-circle',
  },
  {
    step: 2,
    title: 'Upload Photos',
    description: 'Add beautiful photos of your dish and step-by-step process images.',
    icon: 'image',
  },
  {
    step: 3,
    title: 'Search & Enjoy',
    description: 'Find any recipe instantly by ingredient, category, or cuisine type.',
    icon: 'utensils-crossed',
  },
];

// Sample/seed recipes for demo
const MANUAL_RECIPES = [
  {
    id: 'sample-1',
    title: 'CHICKEN BIRYANI',
    description: 'Fragrant basmati rice layered with tender chicken, aromatic spices, and caramelized onions. A royal feast from the Mughal kitchens.',
    ingredients: [
      { id: 'i1', name: 'Basmati Rice', quantity: '2', unit: 'cups', isOptional: false },
      { id: 'i2', name: 'Chicken', quantity: '500', unit: 'grams', isOptional: false },
      { id: 'i3', name: 'Onions', quantity: '3', unit: 'large', isOptional: false },
      { id: 'i4', name: 'Yogurt', quantity: '1', unit: 'cup', isOptional: false },
      { id: 'i5', name: 'Biryani Masala', quantity: '2', unit: 'tbsp', isOptional: false },
      { id: 'i6', name: 'Saffron', quantity: '1', unit: 'pinch', isOptional: true },
      { id: 'i7', name: 'Mint Leaves', quantity: '1', unit: 'bunch', isOptional: false },
    ],
    steps: [
      { id: 's1', stepNumber: 1, instruction: 'Wash and soak basmati rice for 30 minutes. Drain well.', duration: 30 },
      { id: 's2', stepNumber: 2, instruction: 'Marinate chicken with yogurt, biryani masala, salt, and lemon juice for 1 hour.', duration: 60 },
      { id: 's3', stepNumber: 3, instruction: 'Slice onions thin and fry until deep golden brown. Set aside.', duration: 15 },
      { id: 's4', stepNumber: 4, instruction: 'Par-boil rice with whole spices until 70% done. Drain.', duration: 10 },
      { id: 's5', stepNumber: 5, instruction: 'Layer marinated chicken, then rice, then fried onions, mint, and saffron milk.', duration: 5 },
      { id: 's6', stepNumber: 6, instruction: 'Seal with dough and cook on dum (very low heat) for 25 minutes.', duration: 25, tip: 'Do not open the lid during dum cooking.' },
    ],
    cookingTime: 90,
    prepTime: 45,
    servings: 6,
    category: 'Lunch' as const,
    cuisine: 'North Indian' as const,
    diet: 'Non-Veg' as const,
    tags: ['spicy', 'festive', 'rice', 'aromatic'],
    images: [],
    coverImage: '/images/chicken-biryani.png',
    isFavorite: true,
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 5,
    difficulty: 'Hard' as const,
    calories: 450,
    rating: 4.8,
    viewCount: 234,
  },
  {
    id: 'sample-2',
    title: 'MASALA DOSA',
    description: 'Crispy golden crepe made from fermented rice and lentil batter, filled with spiced potato masala. South India\'s crown jewel.',
    ingredients: [
      { id: 'i1', name: 'Dosa Batter', quantity: '3', unit: 'cups', isOptional: false },
      { id: 'i2', name: 'Potatoes', quantity: '4', unit: 'medium', isOptional: false },
      { id: 'i3', name: 'Onions', quantity: '2', unit: 'medium', isOptional: false },
      { id: 'i4', name: 'Mustard Seeds', quantity: '1', unit: 'tsp', isOptional: false },
      { id: 'i5', name: 'Turmeric', quantity: '0.5', unit: 'tsp', isOptional: false },
      { id: 'i6', name: 'Green Chilies', quantity: '3', unit: 'pieces', isOptional: false },
      { id: 'i7', name: 'Curry Leaves', quantity: '1', unit: 'sprig', isOptional: false },
    ],
    steps: [
      { id: 's1', stepNumber: 1, instruction: 'Boil potatoes, peel, and mash coarsely.', duration: 20 },
      { id: 's2', stepNumber: 2, instruction: 'Heat oil, add mustard seeds, curry leaves, green chilies, and onions.', duration: 5 },
      { id: 's3', stepNumber: 3, instruction: 'Add turmeric and mashed potatoes. Mix well and season.', duration: 5 },
      { id: 's4', stepNumber: 4, instruction: 'Heat a cast iron tawa. Pour batter and spread in circular motion.', duration: 3 },
      { id: 's5', stepNumber: 5, instruction: 'Drizzle oil, cook until golden and crispy. Add potato filling and fold.', duration: 3, tip: 'The tawa should be very hot for crispy dosa.' },
    ],
    cookingTime: 25,
    prepTime: 15,
    servings: 4,
    category: 'Breakfast' as const,
    cuisine: 'South Indian' as const,
    diet: 'Veg' as const,
    tags: ['crispy', 'healthy', 'traditional'],
    images: [],
    coverImage: '/images/masala-dosa.png',
    isFavorite: false,
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 86400000 * 3,
    difficulty: 'Medium' as const,
    calories: 280,
    rating: 4.9,
    viewCount: 456,
  },
  {
    id: 'sample-3',
    title: 'PANEER BUTTER MASALA',
    description: 'Silky tomato-cream gravy with soft paneer cubes, kissed with butter and kasuri methi. Restaurant-style richness at home.',
    ingredients: [
      { id: 'i1', name: 'Paneer', quantity: '250', unit: 'grams', isOptional: false },
      { id: 'i2', name: 'Tomatoes', quantity: '4', unit: 'large', isOptional: false },
      { id: 'i3', name: 'Cashews', quantity: '10', unit: 'pieces', isOptional: false },
      { id: 'i4', name: 'Butter', quantity: '3', unit: 'tbsp', isOptional: false },
      { id: 'i5', name: 'Cream', quantity: '0.5', unit: 'cup', isOptional: false },
      { id: 'i6', name: 'Kasuri Methi', quantity: '1', unit: 'tbsp', isOptional: false },
      { id: 'i7', name: 'Garam Masala', quantity: '1', unit: 'tsp', isOptional: false },
    ],
    steps: [
      { id: 's1', stepNumber: 1, instruction: 'Blanch tomatoes and cashews. Blend into smooth paste.', duration: 10 },
      { id: 's2', stepNumber: 2, instruction: 'Heat butter, add paste. Cook until oil separates.', duration: 15 },
      { id: 's3', stepNumber: 3, instruction: 'Add spices — red chili, garam masala, salt, sugar.', duration: 2 },
      { id: 's4', stepNumber: 4, instruction: 'Add cream, mix well. Add paneer cubes.', duration: 5 },
      { id: 's5', stepNumber: 5, instruction: 'Crush kasuri methi and sprinkle. Simmer 5 minutes.', duration: 5, tip: 'Add a pinch of sugar to balance the tomato acidity.' },
    ],
    cookingTime: 35,
    prepTime: 15,
    servings: 4,
    category: 'Dinner' as const,
    cuisine: 'North Indian' as const,
    diet: 'Veg' as const,
    tags: ['creamy', 'rich', 'restaurant-style'],
    images: [],
    coverImage: '/images/paneer-butter-masala.png',
    isFavorite: true,
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 2,
    difficulty: 'Easy' as const,
    calories: 380,
    rating: 4.7,
    viewCount: 189,
  },
  {
    id: 'sample-4',
    title: 'GULAB JAMUN',
    description: 'Golden-fried milk dumplings soaked in rose-cardamom sugar syrup. The ultimate Indian dessert experience.',
    ingredients: [
      { id: 'i1', name: 'Khoya/Mawa', quantity: '200', unit: 'grams', isOptional: false },
      { id: 'i2', name: 'All-Purpose Flour', quantity: '3', unit: 'tbsp', isOptional: false },
      { id: 'i3', name: 'Sugar', quantity: '2', unit: 'cups', isOptional: false },
      { id: 'i4', name: 'Cardamom', quantity: '4', unit: 'pods', isOptional: false },
      { id: 'i5', name: 'Rose Water', quantity: '1', unit: 'tsp', isOptional: true },
      { id: 'i6', name: 'Ghee', quantity: 'for', unit: 'frying', isOptional: false },
    ],
    steps: [
      { id: 's1', stepNumber: 1, instruction: 'Make sugar syrup with water, sugar, cardamom, and rose water. Keep warm.', duration: 15 },
      { id: 's2', stepNumber: 2, instruction: 'Crumble khoya, add flour. Knead into smooth dough using milk.', duration: 10 },
      { id: 's3', stepNumber: 3, instruction: 'Roll into smooth, crack-free balls.', duration: 10, tip: 'If dough cracks, add a few drops of milk.' },
      { id: 's4', stepNumber: 4, instruction: 'Deep fry on LOW heat until deep golden brown all over.', duration: 15, tip: 'Low heat is crucial — high heat will leave them raw inside.' },
      { id: 's5', stepNumber: 5, instruction: 'Soak fried balls in warm syrup for at least 2 hours.', duration: 120 },
    ],
    cookingTime: 60,
    prepTime: 30,
    servings: 20,
    category: 'Dessert' as const,
    cuisine: 'North Indian' as const,
    diet: 'Veg' as const,
    tags: ['sweet', 'festive', 'traditional', 'rich'],
    images: [],
    coverImage: '/images/gulab-jamun.png',
    isFavorite: false,
    createdAt: Date.now() - 86400000,
    updatedAt: Date.now() - 86400000,
    difficulty: 'Medium' as const,
    calories: 150,
    rating: 4.6,
    viewCount: 312,
  },
  {
    id: 'sample-5',
    title: 'DRAGON CHICKEN',
    description: 'Crispy fried chicken tossed in a fiery sweet-sour-spicy Indo-Chinese sauce with bell peppers and spring onions.',
    ingredients: [
      { id: 'i1', name: 'Chicken', quantity: '500', unit: 'grams', isOptional: false },
      { id: 'i2', name: 'Cornflour', quantity: '4', unit: 'tbsp', isOptional: false },
      { id: 'i3', name: 'Soy Sauce', quantity: '2', unit: 'tbsp', isOptional: false },
      { id: 'i4', name: 'Chili Sauce', quantity: '3', unit: 'tbsp', isOptional: false },
      { id: 'i5', name: 'Bell Peppers', quantity: '2', unit: 'medium', isOptional: false },
      { id: 'i6', name: 'Spring Onions', quantity: '4', unit: 'stalks', isOptional: false },
      { id: 'i7', name: 'Garlic', quantity: '8', unit: 'cloves', isOptional: false },
    ],
    steps: [
      { id: 's1', stepNumber: 1, instruction: 'Marinate chicken with cornflour, egg, salt, and pepper.', duration: 30 },
      { id: 's2', stepNumber: 2, instruction: 'Deep fry chicken pieces until golden and crispy.', duration: 15 },
      { id: 's3', stepNumber: 3, instruction: 'In a wok, sauté garlic, ginger, and dried red chilies.', duration: 3 },
      { id: 's4', stepNumber: 4, instruction: 'Add soy sauce, chili sauce, vinegar, and sugar. Cook 2 min.', duration: 3 },
      { id: 's5', stepNumber: 5, instruction: 'Toss in fried chicken, bell peppers, spring onions. Stir-fry high heat.', duration: 5, tip: 'Keep the flame high for that smoky wok flavor.' },
    ],
    cookingTime: 40,
    prepTime: 35,
    servings: 4,
    category: 'Snacks' as const,
    cuisine: 'Chinese' as const,
    diet: 'Non-Veg' as const,
    tags: ['spicy', 'crispy', 'indo-chinese', 'party'],
    images: [],
    coverImage: '/images/dragon-chicken.png',
    isFavorite: true,
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now() - 86400000 * 4,
    difficulty: 'Medium' as const,
    calories: 420,
    rating: 4.5,
    viewCount: 278,
  },
  {
    id: 'sample-6',
    title: 'MANGO LASSI',
    description: 'Creamy, chilled yogurt smoothie blended with ripe Alphonso mangoes, sugar, and a hint of cardamom.',
    ingredients: [
      { id: 'i1', name: 'Mango Pulp', quantity: '1', unit: 'cup', isOptional: false },
      { id: 'i2', name: 'Yogurt', quantity: '1', unit: 'cup', isOptional: false },
      { id: 'i3', name: 'Sugar', quantity: '2', unit: 'tbsp', isOptional: false },
      { id: 'i4', name: 'Cardamom Powder', quantity: '0.25', unit: 'tsp', isOptional: true },
      { id: 'i5', name: 'Ice Cubes', quantity: '4', unit: 'cubes', isOptional: false },
    ],
    steps: [
      { id: 's1', stepNumber: 1, instruction: 'Blend mango pulp, yogurt, sugar, and cardamom until smooth.', duration: 2 },
      { id: 's2', stepNumber: 2, instruction: 'Add ice cubes and blend again for 30 seconds.', duration: 1 },
      { id: 's3', stepNumber: 3, instruction: 'Pour into tall glass. Garnish with saffron strands and pistachios.', duration: 1, tip: 'Use chilled yogurt for the best texture.' },
    ],
    cookingTime: 5,
    prepTime: 5,
    servings: 2,
    category: 'Beverage' as const,
    cuisine: 'North Indian' as const,
    diet: 'Veg' as const,
    tags: ['quick', 'refreshing', 'summer', 'healthy'],
    images: [],
    coverImage: '/images/mango-lassi.png',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    difficulty: 'Easy' as const,
    calories: 180,
    rating: 4.9,
    viewCount: 567,
  },
  {
    id: 'sample-7',
    title: 'PAZHAM PORI (BANANA FRITTERS)',
    description: 'Traditional South Indian tea-time snack made with ripe Nendran bananas dipped in a smooth, sweet flour batter and deep-fried to golden perfection.',
    ingredients: [
      { id: 'i1', name: 'Ripe Bananas (Nendran)', quantity: '3', unit: 'pieces', isOptional: false },
      { id: 'i2', name: 'All-Purpose Flour (Maida)', quantity: '1', unit: 'cup', isOptional: false },
      { id: 'i3', name: 'Rice Flour', quantity: '2', unit: 'tbsp', isOptional: true },
      { id: 'i4', name: 'Sugar', quantity: '1.5', unit: 'tbsp', isOptional: false },
      { id: 'i5', name: 'Turmeric Powder', quantity: '0.25', unit: 'tsp', isOptional: false },
      { id: 'i6', name: 'Cardamom Powder', quantity: '0.25', unit: 'tsp', isOptional: true },
      { id: 'i7', name: 'Coconut Oil', quantity: 'for', unit: 'frying', isOptional: false },
    ],
    steps: [
      { id: 's1', stepNumber: 1, instruction: 'Peel the ripe bananas and slice them thin lengthwise into 2 or 3 flat pieces.', duration: 5 },
      { id: 's2', stepNumber: 2, instruction: 'Make a smooth, semi-thick batter by mixing all-purpose flour, rice flour, sugar, turmeric powder, cardamom powder, and water.', duration: 5 },
      { id: 's3', stepNumber: 3, instruction: 'Heat coconut oil in a deep frying pan on medium heat.', duration: 5 },
      { id: 's4', stepNumber: 4, instruction: 'Dip each banana slice into the batter, coating it completely, and gently lower it into the hot oil.', duration: 2 },
      { id: 's5', stepNumber: 5, instruction: 'Deep fry both sides until they turn crispy and golden brown. Drain on paper towels.', duration: 6, tip: 'Ensure the oil is at medium temperature; too hot will burn the outer batter before cooking the banana.' },
    ],
    cookingTime: 15,
    prepTime: 10,
    servings: 4,
    category: 'Snacks' as const,
    cuisine: 'South Indian' as const,
    diet: 'Veg' as const,
    tags: ['sweet', 'crispy', 'snack', 'banana', 'traditional'],
    images: [],
    coverImage: '/images/pazham-pori.png',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    difficulty: 'Easy' as const,
    calories: 220,
    rating: 4.8,
    viewCount: 142,
  },
  {
    id: 'sample-8',
    title: 'CLASSIC BANANA BREAD',
    description: 'Super moist, tender, and flavor-packed banana bread recipe loaded with ripe bananas, vanilla, and cinnamon warmth.',
    ingredients: [
      { id: 'i1', name: 'Ripe Bananas', quantity: '3', unit: 'medium', isOptional: false },
      { id: 'i2', name: 'Melted Butter', quantity: '0.33', unit: 'cup', isOptional: false },
      { id: 'i3', name: 'Sugar', quantity: '0.75', unit: 'cup', isOptional: false },
      { id: 'i4', name: 'Egg (beaten)', quantity: '1', unit: 'large', isOptional: false },
      { id: 'i5', name: 'Vanilla Extract', quantity: '1', unit: 'tsp', isOptional: true },
      { id: 'i6', name: 'Baking Soda', quantity: '1', unit: 'tsp', isOptional: false },
      { id: 'i7', name: 'All-Purpose Flour', quantity: '1.5', unit: 'cups', isOptional: false },
      { id: 'i8', name: 'Cinnamon Powder', quantity: '0.5', unit: 'tsp', isOptional: true },
    ],
    steps: [
      { id: 's1', stepNumber: 1, instruction: 'Preheat oven to 350°F (175°C) and grease a 4x8 inch loaf pan.', duration: 10 },
      { id: 's2', stepNumber: 2, instruction: 'In a mixing bowl, mash the ripe bananas with a fork until smooth.', duration: 5 },
      { id: 's3', stepNumber: 3, instruction: 'Stir the melted butter into the mashed bananas.', duration: 2 },
      { id: 's4', stepNumber: 4, instruction: 'Mix in sugar, egg, vanilla extract, and cinnamon.', duration: 3 },
      { id: 's5', stepNumber: 5, instruction: 'Sprinkle baking soda and pinch of salt, then gently stir in the flour until just combined.', duration: 4 },
      { id: 's6', stepNumber: 6, instruction: 'Pour the batter into your prepared loaf pan. Bake for 50 to 60 minutes.', duration: 60, tip: 'A toothpick inserted into the center should come out clean when done.' },
    ],
    cookingTime: 60,
    prepTime: 15,
    servings: 10,
    category: 'Breakfast' as const,
    cuisine: 'American' as const,
    diet: 'Veg' as const,
    tags: ['sweet', 'moist', 'baking', 'banana', 'healthy'],
    images: [],
    coverImage: '/images/banana-bread.png',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    difficulty: 'Easy' as const,
    calories: 250,
    rating: 4.7,
    viewCount: 98,
  },
  {
    id: 'sample-9',
    title: 'CARAMELIZED BANANA PANCAKES',
    description: 'Fluffy, thick pancakes topped with sweet, sticky caramelized bananas. The ultimate weekend brunch indulgence.',
    ingredients: [
      { id: 'i1', name: 'Ripe Bananas', quantity: '2', unit: 'sliced', isOptional: false },
      { id: 'i2', name: 'All-Purpose Flour', quantity: '1', unit: 'cup', isOptional: false },
      { id: 'i3', name: 'Milk', quantity: '0.75', unit: 'cup', isOptional: false },
      { id: 'i4', name: 'Egg', quantity: '1', unit: 'large', isOptional: false },
      { id: 'i5', name: 'Brown Sugar', quantity: '3', unit: 'tbsp', isOptional: false },
      { id: 'i6', name: 'Butter', quantity: '2', unit: 'tbsp', isOptional: false },
      { id: 'i7', name: 'Baking Powder', quantity: '1', unit: 'tsp', isOptional: false },
    ],
    steps: [
      { id: 's1', stepNumber: 1, instruction: 'Whisk flour, baking powder, and sugar. Mix in milk, egg, and melted butter until smooth.', duration: 5 },
      { id: 's2', stepNumber: 2, instruction: 'Cook pancakes on a buttered griddle until golden on both sides.', duration: 8 },
      { id: 's3', stepNumber: 3, instruction: 'In another pan, melt butter and brown sugar. Add banana slices and caramelize for 3 minutes.', duration: 3, tip: 'Gently toss the bananas so they do not break.' },
      { id: 's4', stepNumber: 4, instruction: 'Serve warm pancakes topped with the warm caramelized banana syrup.', duration: 2 },
    ],
    cookingTime: 18,
    prepTime: 10,
    servings: 3,
    category: 'Breakfast' as const,
    cuisine: 'American' as const,
    diet: 'Veg' as const,
    tags: ['sweet', 'brunch', 'fluffy', 'banana'],
    images: [],
    coverImage: '/images/banana-pancakes.png',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    difficulty: 'Easy' as const,
    calories: 320,
    rating: 4.8,
    viewCount: 110,
  },
  {
    id: 'sample-10',
    title: 'BANANA PAYASAM (PRATHAMAN)',
    description: 'A rich Kerala-style dessert made with sweet bananas cooked in dark jaggery syrup and creamy coconut milk, flavored with cardamom and dry ginger.',
    ingredients: [
      { id: 'i1', name: 'Ripe Bananas (Nendran)', quantity: '2', unit: 'chopped', isOptional: false },
      { id: 'i2', name: 'Jaggery (Gud)', quantity: '200', unit: 'grams', isOptional: false },
      { id: 'i3', name: 'Coconut Milk (Thick)', quantity: '1', unit: 'cup', isOptional: false },
      { id: 'i4', name: 'Coconut Milk (Thin)', quantity: '2', unit: 'cups', isOptional: false },
      { id: 'i5', name: 'Ghee', quantity: '2', unit: 'tbsp', isOptional: false },
      { id: 'i6', name: 'Cashews & Raisins', quantity: '10', unit: 'pieces', isOptional: true },
      { id: 'i7', name: 'Cardamom Powder', quantity: '0.5', unit: 'tsp', isOptional: false },
    ],
    steps: [
      { id: 's1', stepNumber: 1, instruction: 'Sauté chopped bananas in ghee until soft and golden.', duration: 8 },
      { id: 's2', stepNumber: 2, instruction: 'Add jaggery syrup and cook until the mixture thickens.', duration: 10 },
      { id: 's3', stepNumber: 3, instruction: 'Pour in the thin coconut milk and simmer for 5 minutes.', duration: 5 },
      { id: 's4', stepNumber: 4, instruction: 'Add the thick coconut milk, cardamom powder, and ginger powder. Turn off heat immediately.', duration: 2, tip: 'Do not boil after adding thick coconut milk, otherwise it will curdle.' },
      { id: 's5', stepNumber: 5, instruction: 'Garnish with fried cashews, raisins, and coconut bites.', duration: 2 },
    ],
    cookingTime: 27,
    prepTime: 15,
    servings: 5,
    category: 'Dessert' as const,
    cuisine: 'South Indian' as const,
    diet: 'Veg' as const,
    tags: ['sweet', 'creamy', 'traditional', 'coconut', 'banana'],
    images: [],
    coverImage: '/images/banana-payasam.png',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    difficulty: 'Medium' as const,
    calories: 290,
    rating: 4.9,
    viewCount: 165,
  },
  {
    id: 'sample-11',
    title: 'CRISPY BANANA CHIPS',
    description: 'Wafer-thin, crunchy salted banana chips fried in pure coconut oil. A legendary South Indian snack.',
    ingredients: [
      { id: 'i1', name: 'Raw Bananas (Nendran)', quantity: '4', unit: 'large', isOptional: false },
      { id: 'i2', name: 'Coconut Oil', quantity: 'for', unit: 'deep frying', isOptional: false },
      { id: 'i3', name: 'Turmeric Powder', quantity: '1', unit: 'tsp', isOptional: false },
      { id: 'i4', name: 'Salt', quantity: '2', unit: 'tsp', isOptional: false },
      { id: 'i5', name: 'Water', quantity: '0.25', unit: 'cup', isOptional: false },
    ],
    steps: [
      { id: 's1', stepNumber: 1, instruction: 'Peel the raw bananas and soak them in turmeric water for 15 minutes, then wipe completely dry.', duration: 20 },
      { id: 's2', stepNumber: 2, instruction: 'Dissolve salt in a quarter cup of water.', duration: 2 },
      { id: 's3', stepNumber: 3, instruction: 'Heat coconut oil on high in a deep wok.', duration: 8 },
      { id: 's4', stepNumber: 4, instruction: 'Slice bananas directly into the hot oil in thin round wafers.', duration: 3 },
      { id: 's5', stepNumber: 5, instruction: 'Sprinkle 1 tsp of salt water into the oil. Fry until bubbling stops and chips are crispy.', duration: 5, tip: 'Be careful as oil will splutter when salt water is added.' },
    ],
    cookingTime: 38,
    prepTime: 20,
    servings: 8,
    category: 'Snacks' as const,
    cuisine: 'South Indian' as const,
    diet: 'Veg' as const,
    tags: ['crispy', 'crunchy', 'snack', 'salted', 'banana'],
    images: [],
    coverImage: '/images/banana-chips.png',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    difficulty: 'Easy' as const,
    calories: 140,
    rating: 4.8,
    viewCount: 224,
  },
  {
    id: 'sample-12',
    title: 'BANANA BERRY SMOOTHIE',
    description: 'Chilled, creamy and healthy smoothie blending sweet ripe bananas, mixed berries, Greek yogurt, and a drizzle of honey.',
    ingredients: [
      { id: 'i1', name: 'Ripe Banana', quantity: '1', unit: 'large', isOptional: false },
      { id: 'i2', name: 'Mixed Berries (Frozen)', quantity: '0.5', unit: 'cup', isOptional: false },
      { id: 'i3', name: 'Greek Yogurt', quantity: '0.5', unit: 'cup', isOptional: false },
      { id: 'i4', name: 'Almond Milk', quantity: '0.5', unit: 'cup', isOptional: false },
      { id: 'i5', name: 'Honey', quantity: '1', unit: 'tbsp', isOptional: true },
    ],
    steps: [
      { id: 's1', stepNumber: 1, instruction: 'Add sliced banana, berries, yogurt, milk, and honey to a high-speed blender.', duration: 2 },
      { id: 's2', stepNumber: 2, instruction: 'Blend until completely smooth and creamy.', duration: 1 },
      { id: 's3', stepNumber: 3, instruction: 'Pour into glasses and serve cold, garnished with fresh berries.', duration: 1, tip: 'Using a frozen banana makes the smoothie thicker and creamier.' },
    ],
    cookingTime: 4,
    prepTime: 4,
    servings: 2,
    category: 'Beverage' as const,
    cuisine: 'North Indian' as const,
    diet: 'Veg' as const,
    tags: ['quick', 'healthy', 'smoothie', 'breakfast', 'banana'],
    images: [],
    coverImage: '/images/banana-smoothie.png',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    difficulty: 'Easy' as const,
  },
];

const EXTRA_RECIPES_DATA = [
  {
    title: 'BUTTER CHICKEN',
    description: 'Tender chicken pieces cooked in a creamy, rich spiced tomato gravy. A classic North Indian delicacy.',
    category: 'Dinner',
    cuisine: 'North Indian',
    diet: 'Non-Veg',
    coverImage: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
    tags: ['creamy', 'rich', 'butter', 'chicken'],
  },
  {
    title: 'MARGHERITA PIZZA',
    description: 'Classic Italian pizza topped with fresh tomato sauce, mozzarella cheese, and fresh basil leaves.',
    category: 'Dinner',
    cuisine: 'Italian',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=600&q=80',
    tags: ['cheese', 'classic', 'baked', 'basil'],
  },
  {
    title: 'PASTA CARBONARA',
    description: 'Creamy Roman pasta dish made with eggs, hard cheese, cured pork, and black pepper.',
    category: 'Dinner',
    cuisine: 'Italian',
    diet: 'Non-Veg',
    coverImage: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=600&q=80',
    tags: ['creamy', 'pasta', 'bacon', 'classic'],
  },
  {
    title: 'PAD THAI',
    description: 'Stir-fried rice noodles with eggs, tofu or chicken, peanuts, bean sprouts, and a sweet-savory tamarind sauce.',
    category: 'Lunch',
    cuisine: 'Thai',
    diet: 'Non-Veg',
    coverImage: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?auto=format&fit=crop&w=600&q=80',
    tags: ['noodles', 'sweet-savory', 'peanuts', 'spicy'],
  },
  {
    title: 'TACOS AL PASTOR',
    description: 'Mexican street-style corn tortillas filled with spit-grilled pork marinated with chilies and pineapple.',
    category: 'Lunch',
    cuisine: 'Mexican',
    diet: 'Non-Veg',
    coverImage: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80',
    tags: ['spicy', 'pineapple', 'street-food', 'pork'],
  },
  {
    title: 'SUSHI PLATTER',
    description: 'Assorted premium sushi rolls, nigiri, and sashimi served with pickled ginger, wasabi, and soy sauce.',
    category: 'Lunch',
    cuisine: 'Japanese',
    diet: 'Non-Veg',
    coverImage: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=600&q=80',
    tags: ['seafood', 'fresh', 'rice', 'wasabi'],
  },
  {
    title: 'TOM YUM SOUP',
    description: 'Hot and sour Thai soup cooked with shrimp, lemongrass, galangal, kaffir lime leaves, and chili.',
    category: 'Appetizer',
    cuisine: 'Thai',
    diet: 'Non-Veg',
    coverImage: 'https://images.unsplash.com/photo-1548940740-204726a19db3?auto=format&fit=crop&w=600&q=80',
    tags: ['hot-sour', 'soup', 'shrimp', 'herbal'],
  },
  {
    title: 'PANEER TIKKA',
    description: 'Marinated paneer cubes grilled to perfection with bell peppers and onions in a traditional tandoor.',
    category: 'Appetizer',
    cuisine: 'North Indian',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80',
    tags: ['grilled', 'spicy', 'tandoori', 'paneer'],
  },
  {
    title: 'IDLI SAMBAR',
    description: 'Soft, fluffy steamed rice cakes served with aromatic lentil vegetable stew (sambar) and coconut chutney.',
    category: 'Breakfast',
    cuisine: 'South Indian',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    tags: ['healthy', 'steamed', 'fermented', 'traditional'],
  },
  {
    title: 'MEDU VADA',
    description: 'Crispy, deep-fried black lentil fritters donut-shaped and served with warm sambar and fresh chutney.',
    category: 'Breakfast',
    cuisine: 'South Indian',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=600&q=80',
    tags: ['crispy', 'savory', 'fried', 'traditional'],
  },
  {
    title: 'FILTER COFFEE',
    description: 'Strong, aromatic South Indian chicory-blend coffee frothed with boiling milk in a brass tumbler.',
    category: 'Beverage',
    cuisine: 'Tamil',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    tags: ['aromatic', 'caffeine', 'traditional', 'frothy'],
  },
  {
    title: 'GARLIC BREAD',
    description: 'Toasted baguette slices brushed with butter, minced garlic, herbs, and melted mozzarella cheese.',
    category: 'Appetizer',
    cuisine: 'Italian',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?auto=format&fit=crop&w=600&q=80',
    tags: ['garlic', 'cheese', 'baked', 'starter'],
  },
  {
    title: 'FRENCH FRIES',
    description: 'Crispy, golden-brown deep-fried potato batons tossed with sea salt and served with ketchup.',
    category: 'Snacks',
    cuisine: 'Continental',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
    tags: ['crispy', 'potato', 'classic', 'kids-favorite'],
  },
  {
    title: 'CHILI PANEER',
    description: 'Indo-Chinese street-style paneer cubes tossed with bell peppers and onions in a spicy soy-garlic sauce.',
    category: 'Snacks',
    cuisine: 'Chinese',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&w=600&q=80',
    tags: ['spicy', 'saucy', 'paneer', 'chinese'],
  },
  {
    title: 'VEG FRIED RICE',
    description: 'Aromatic basmati rice stir-fried in a hot wok with finely chopped vegetables, garlic, and soy sauce.',
    category: 'Lunch',
    cuisine: 'Chinese',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80',
    tags: ['rice', 'stir-fried', 'wok', 'healthy'],
  },
  {
    title: 'CHOCOLATE LAVA CAKE',
    description: 'Rich chocolate cake with a warm, liquid chocolate molten center. Serving heaven on a plate.',
    category: 'Dessert',
    cuisine: 'Continental',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80',
    tags: ['sweet', 'chocolate', 'molten', 'warm'],
  },
  {
    title: 'CLASSIC APPLE PIE',
    description: 'Golden, flaky pastry crust filled with spiced warm apples, served with vanilla ice cream.',
    category: 'Dessert',
    cuisine: 'Continental',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=600&q=80',
    tags: ['sweet', 'baked', 'apple', 'traditional'],
  },
  {
    title: 'CAESAR SALAD',
    description: 'Crisp romaine lettuce tossed with parmesan cheese, crunchy croutons, and premium Caesar dressing.',
    category: 'Appetizer',
    cuisine: 'Continental',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=600&q=80',
    tags: ['fresh', 'salad', 'healthy', 'low-carb'],
  },
  {
    title: 'MINESTRONE SOUP',
    description: 'Hearty Italian vegetable soup with beans, onions, celery, carrots, stock, tomatoes, and pasta.',
    category: 'Appetizer',
    cuisine: 'Italian',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1547592165-e1d17fed6006?auto=format&fit=crop&w=600&q=80',
    tags: ['soup', 'healthy', 'vegetables', 'warm'],
  },
  {
    title: 'TOMATO BRUSCHETTA',
    description: 'Grilled bread rubbed with garlic and topped with diced fresh tomatoes, olive oil, basil, and balsamic.',
    category: 'Appetizer',
    cuisine: 'Italian',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1572656631137-7935297eff55?auto=format&fit=crop&w=600&q=80',
    tags: ['fresh', 'basil', 'starter', 'easy'],
  },
  {
    title: 'FRESH LEMONADE',
    description: 'Chilled, refreshing beverage made of squeezed fresh lemon juice, water, sugar, and mint leaves.',
    category: 'Beverage',
    cuisine: 'Other',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    tags: ['quick', 'chilled', 'sour-sweet', 'summer'],
  },
  {
    title: 'PEACH ICED TEA',
    description: 'Brewed black tea infused with sweet peach syrup, served over ice with fresh mint garnish.',
    category: 'Beverage',
    cuisine: 'Other',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80',
    tags: ['iced', 'tea', 'peach', 'refreshing'],
  },
  {
    title: 'PUNJABI SAMOSA',
    description: 'Flaky pastry shells stuffed with spiced potatoes, green peas, and served with tamarind chutney.',
    category: 'Snacks',
    cuisine: 'North Indian',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&w=600&q=80',
    tags: ['spicy', 'crispy', 'snack', 'favorite'],
  },
  {
    title: 'ONION PAKODA',
    description: 'Crispy, deep-fried sliced onion fritters mixed with chickpea flour and local spices.',
    category: 'Snacks',
    cuisine: 'Tamil',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1589302168068-964664d93dc9?auto=format&fit=crop&w=600&q=80',
    tags: ['crispy', 'tea-time', 'onion', 'quick'],
  },
  {
    title: 'RAVA UPMA',
    description: 'Traditional South Indian roasted semolina breakfast dish cooked with vegetables, mustard, and curry leaves.',
    category: 'Breakfast',
    cuisine: 'South Indian',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    tags: ['healthy', 'semolina', 'traditional', 'quick'],
  },
  {
    title: 'INDORI POHA',
    description: 'Light, fluffy flattened rice seasoned with mustard seeds, turmeric, green chilies, and topped with sev.',
    category: 'Breakfast',
    cuisine: 'North Indian',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&w=600&q=80',
    tags: ['light', 'breakfast', 'steamed', 'quick'],
  },
  {
    title: 'BELGIAN WAFFLES',
    description: 'Crispy, light waffles with deep grids, dusted with powdered sugar and drizzled with maple syrup.',
    category: 'Breakfast',
    cuisine: 'Continental',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1562376502-6f769499c886?auto=format&fit=crop&w=600&q=80',
    tags: ['sweet', 'baked', 'breakfast', 'belgian'],
  },
  {
    title: 'AVOCADO TOAST',
    description: 'Sourdough toast topped with creamy mashed avocado, red pepper flakes, and a drizzle of olive oil.',
    category: 'Breakfast',
    cuisine: 'Continental',
    diet: 'Vegan',
    coverImage: 'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?auto=format&fit=crop&w=600&q=80',
    tags: ['healthy', 'avocado', 'sourdough', 'vegan'],
  },
  {
    title: 'MIXED FRUIT SALAD',
    description: 'A colorful medley of fresh, seasonal sliced fruits tossed with a sweet lime-mint dressing.',
    category: 'Dessert',
    cuisine: 'Other',
    diet: 'Vegan',
    coverImage: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&w=600&q=80',
    tags: ['healthy', 'fresh', 'fruits', 'low-cal'],
  },
  {
    title: 'VEG SPRING ROLLS',
    description: 'Crispy rolled wrappers stuffed with stir-fried cabbage, carrots, and spring onions, fried golden.',
    category: 'Appetizer',
    cuisine: 'Chinese',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    tags: ['crispy', 'fried', 'chinese', 'starter'],
  },
  {
    title: 'LOADED NACHOS',
    description: 'Crispy corn tortilla chips loaded with warm melted cheese, black beans, jalapeños, and sour cream.',
    category: 'Snacks',
    cuisine: 'Mexican',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?auto=format&fit=crop&w=600&q=80',
    tags: ['cheese', 'crispy', 'party', 'mexican'],
  },
  {
    title: 'CHEESY QUESADILLA',
    description: 'Toasted flour tortillas folded and packed with melted cheddar-jack cheese and mild spices.',
    category: 'Snacks',
    cuisine: 'Mexican',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?auto=format&fit=crop&w=600&q=80',
    tags: ['cheese', 'toasted', 'mexican', 'quick'],
  },
  {
    title: 'EGG-FREE BROWNIE',
    description: 'Fudgy, rich chocolate brownie baked without eggs, served warm with a drizzle of chocolate sauce.',
    category: 'Dessert',
    cuisine: 'Continental',
    diet: 'Egg-Free',
    coverImage: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80',
    tags: ['sweet', 'chocolate', 'fudgy', 'egg-free'],
  },
  {
    title: 'CLASSIC CHURROS',
    description: 'Deep-fried piped choux pastry rolled in cinnamon sugar, served with a rich chocolate dipping sauce.',
    category: 'Dessert',
    cuisine: 'Mexican',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1568254183919-78a4f43a2877?auto=format&fit=crop&w=600&q=80',
    tags: ['sweet', 'fried', 'cinnamon', 'dessert'],
  },
  {
    title: 'FRENCH MACARONS',
    description: 'Delicate meringue-based sandwich cookies with a sweet chocolate ganache filling.',
    category: 'Dessert',
    cuisine: 'Continental',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1569864358642-9d1684040f43?auto=format&fit=crop&w=600&q=80',
    tags: ['sweet', 'delicate', 'cookies', 'colorful'],
  },
  {
    title: 'STRAWBERRY MILKSHAKE',
    description: 'Creamy, chilled milkshake blended with fresh strawberries and vanilla ice cream.',
    category: 'Beverage',
    cuisine: 'Other',
    diet: 'Veg',
    coverImage: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=600&q=80',
    tags: ['sweet', 'chilled', 'creamy', 'strawberry'],
  },
  {
    title: 'JAPANESE GREEN TEA',
    description: 'Traditional, soothing hot green tea brewed with premium Japanese Sencha tea leaves.',
    category: 'Beverage',
    cuisine: 'Japanese',
    diet: 'Vegan',
    coverImage: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    tags: ['hot', 'healthy', 'detox', 'japanese'],
  },
  {
    title: 'GUACAMOLE & CHIPS',
    description: 'Freshly mashed avocado dip seasoned with onion, tomato, cilantro, lime juice, served with tortilla chips.',
    category: 'Snacks',
    cuisine: 'Mexican',
    diet: 'Vegan',
    coverImage: 'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?auto=format&fit=crop&w=600&q=80',
    tags: ['fresh', 'healthy', 'avocado', 'mexican'],
  },
];

const generateRecipes = (data: typeof EXTRA_RECIPES_DATA): Recipe[] => {
  return data.map((item, idx) => {
    const id = `sample-gen-${idx + 13}`;
    return {
      id,
      title: item.title,
      description: item.description,
      ingredients: [
        { id: 'i1', name: 'Main Ingredient', quantity: '200', unit: 'g', isOptional: false },
        { id: 'i2', name: 'Cooking Oil/Butter', quantity: '2', unit: 'tbsp', isOptional: false },
        { id: 'i3', name: 'Salt & Pepper', quantity: 'to taste', unit: '', isOptional: false },
        { id: 'i4', name: 'Aromatic Spices', quantity: '1', unit: 'tsp', isOptional: true },
        { id: 'i5', name: 'Garnish Herbs', quantity: '1', unit: 'sprig', isOptional: true },
      ],
      steps: [
        { id: 's1', stepNumber: 1, instruction: `Prepare and clean all the fresh ingredients required for ${item.title.toLowerCase()}.`, duration: 10 },
        { id: 's2', stepNumber: 2, instruction: 'Heat oil or butter in a pan, and sauté aromatics until fragrant.', duration: 5 },
        { id: 's3', stepNumber: 3, instruction: 'Add the main ingredients and sauté on medium heat.', duration: 10 },
        { id: 's4', stepNumber: 4, instruction: 'Stir in the sauces or spices, adjust seasoning, and simmer until fully cooked.', duration: 15, tip: 'Keep the temperature low to simmer evenly.' },
        { id: 's5', stepNumber: 5, instruction: 'Garnish with fresh herbs and serve warm.', duration: 2 },
      ],
      cookingTime: 30,
      prepTime: 15,
      servings: 4,
      category: item.category as RecipeCategory,
      cuisine: item.cuisine as CuisineType,
      diet: item.diet as DietType,
      tags: item.tags,
      images: [],
      coverImage: item.coverImage,
      isFavorite: false,
      createdAt: Date.now() - 86400000 * (idx + 1),
      updatedAt: Date.now() - 86400000 * (idx + 1),
      difficulty: (idx % 3 === 0 ? 'Easy' : idx % 3 === 1 ? 'Medium' : 'Hard') as 'Easy' | 'Medium' | 'Hard',
      calories: 150 + (idx * 15) % 350,
      rating: parseFloat((4.2 + (idx * 0.03) % 0.8).toFixed(1)),
      viewCount: 50 + (idx * 12) % 300,
    };
  });
};

export const SAMPLE_RECIPES = [
  ...MANUAL_RECIPES,
  ...generateRecipes(EXTRA_RECIPES_DATA)
];
