// App constants

export const APP_NAME = 'FLAVOUR VAULT';
export const APP_TAGLINE = 'Your Recipes, Beautifully Organized';
export const APP_DESCRIPTION = 'Save, search, and discover recipes with a premium culinary experience.';

export const DB_NAME = 'flavour-vault-db';
export const DB_VERSION = 1;
export const RECIPE_STORE = 'recipes';

export const MAX_IMAGE_SIZE = 1024 * 1024; // 1MB after compression
export const IMAGE_QUALITY = 0.7;
export const MAX_IMAGES_PER_RECIPE = 10;
export const THUMBNAIL_SIZE = 400;

export const STATS = [
  { label: 'Recipes Ready', value: '500+', icon: 'book-open' },
  { label: 'Easy to Use', value: '100%', icon: 'sparkles' },
  { label: 'Completely Free', value: 'Free', icon: 'heart' },
  { label: 'Categories', value: '7+', icon: 'grid-3x3' },
];

export const FEATURES = [
  {
    title: 'Save Unlimited Recipes',
    description: 'Store all your favorite recipes locally. No limits, no subscriptions — your kitchen, your rules.',
    icon: 'book-open',
  },
  {
    title: 'Upload Beautiful Photos',
    description: 'Capture every step of your cooking journey with multiple photos per recipe.',
    icon: 'camera',
  },
  {
    title: 'Smart Ingredient Search',
    description: 'Search by what you have. Find recipes based on ingredients in your kitchen.',
    icon: 'search',
  },
  {
    title: 'Favorite & Organize',
    description: 'Heart your best recipes and organize them by category, cuisine, and diet type.',
    icon: 'heart',
  },
];

export const HOW_IT_WORKS = [
  {
    step: 1,
    title: 'Add Your Recipe',
    description: 'Enter your recipe details — ingredients, steps, cooking time, and more.',
    icon: 'plus-circle',
  },
  {
    step: 2,
    title: 'Upload Photos',
    description: 'Add beautiful photos of your dish and step-by-step process images.',
    icon: 'image',
  },
  {
    step: 3,
    title: 'Search & Enjoy',
    description: 'Find any recipe instantly by ingredient, category, or cuisine type.',
    icon: 'utensils-crossed',
  },
];

// Sample/seed recipes for demo
export const SAMPLE_RECIPES = [
  {
    id: 'sample-1',
    title: 'CHICKEN BIRYANI',
    description: 'Fragrant basmati rice layered with tender chicken, aromatic spices, and caramelized onions. A royal feast from the Mughal kitchens.',
    ingredients: [
      { id: 'i1', name: 'Basmati Rice', quantity: '2', unit: 'cups', isOptional: false },
      { id: 'i2', name: 'Chicken', quantity: '500', unit: 'grams', isOptional: false },
      { id: 'i3', name: 'Onions', quantity: '3', unit: 'large', isOptional: false },
      { id: 'i4', name: 'Yogurt', quantity: '1', unit: 'cup', isOptional: false },
      { id: 'i5', name: 'Biryani Masala', quantity: '2', unit: 'tbsp', isOptional: false },
      { id: 'i6', name: 'Saffron', quantity: '1', unit: 'pinch', isOptional: true },
      { id: 'i7', name: 'Mint Leaves', quantity: '1', unit: 'bunch', isOptional: false },
    ],
    steps: [
      { id: 's1', stepNumber: 1, instruction: 'Wash and soak basmati rice for 30 minutes. Drain well.', duration: 30 },
      { id: 's2', stepNumber: 2, instruction: 'Marinate chicken with yogurt, biryani masala, salt, and lemon juice for 1 hour.', duration: 60 },
      { id: 's3', stepNumber: 3, instruction: 'Slice onions thin and fry until deep golden brown. Set aside.', duration: 15 },
      { id: 's4', stepNumber: 4, instruction: 'Par-boil rice with whole spices until 70% done. Drain.', duration: 10 },
      { id: 's5', stepNumber: 5, instruction: 'Layer marinated chicken, then rice, then fried onions, mint, and saffron milk.', duration: 5 },
      { id: 's6', stepNumber: 6, instruction: 'Seal with dough and cook on dum (very low heat) for 25 minutes.', duration: 25, tip: 'Do not open the lid during dum cooking.' },
    ],
    cookingTime: 90,
    prepTime: 45,
    servings: 6,
    category: 'Lunch' as const,
    cuisine: 'North Indian' as const,
    diet: 'Non-Veg' as const,
    tags: ['spicy', 'festive', 'rice', 'aromatic'],
    images: [],
    coverImage: '/images/chicken-biryani.png',
    isFavorite: true,
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 5,
    difficulty: 'Hard' as const,
    calories: 450,
    rating: 4.8,
    viewCount: 234,
  },
  {
    id: 'sample-2',
    title: 'MASALA DOSA',
    description: 'Crispy golden crepe made from fermented rice and lentil batter, filled with spiced potato masala. South India\'s crown jewel.',
    ingredients: [
      { id: 'i1', name: 'Dosa Batter', quantity: '3', unit: 'cups', isOptional: false },
      { id: 'i2', name: 'Potatoes', quantity: '4', unit: 'medium', isOptional: false },
      { id: 'i3', name: 'Onions', quantity: '2', unit: 'medium', isOptional: false },
      { id: 'i4', name: 'Mustard Seeds', quantity: '1', unit: 'tsp', isOptional: false },
      { id: 'i5', name: 'Turmeric', quantity: '0.5', unit: 'tsp', isOptional: false },
      { id: 'i6', name: 'Green Chilies', quantity: '3', unit: 'pieces', isOptional: false },
      { id: 'i7', name: 'Curry Leaves', quantity: '1', unit: 'sprig', isOptional: false },
    ],
    steps: [
      { id: 's1', stepNumber: 1, instruction: 'Boil potatoes, peel, and mash coarsely.', duration: 20 },
      { id: 's2', stepNumber: 2, instruction: 'Heat oil, add mustard seeds, curry leaves, green chilies, and onions.', duration: 5 },
      { id: 's3', stepNumber: 3, instruction: 'Add turmeric and mashed potatoes. Mix well and season.', duration: 5 },
      { id: 's4', stepNumber: 4, instruction: 'Heat a cast iron tawa. Pour batter and spread in circular motion.', duration: 3 },
      { id: 's5', stepNumber: 5, instruction: 'Drizzle oil, cook until golden and crispy. Add potato filling and fold.', duration: 3, tip: 'The tawa should be very hot for crispy dosa.' },
    ],
    cookingTime: 25,
    prepTime: 15,
    servings: 4,
    category: 'Breakfast' as const,
    cuisine: 'South Indian' as const,
    diet: 'Veg' as const,
    tags: ['crispy', 'healthy', 'traditional'],
    images: [],
    coverImage: '/images/masala-dosa.png',
    isFavorite: false,
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 86400000 * 3,
    difficulty: 'Medium' as const,
    calories: 280,
    rating: 4.9,
    viewCount: 456,
  },
  {
    id: 'sample-3',
    title: 'PANEER BUTTER MASALA',
    description: 'Silky tomato-cream gravy with soft paneer cubes, kissed with butter and kasuri methi. Restaurant-style richness at home.',
    ingredients: [
      { id: 'i1', name: 'Paneer', quantity: '250', unit: 'grams', isOptional: false },
      { id: 'i2', name: 'Tomatoes', quantity: '4', unit: 'large', isOptional: false },
      { id: 'i3', name: 'Cashews', quantity: '10', unit: 'pieces', isOptional: false },
      { id: 'i4', name: 'Butter', quantity: '3', unit: 'tbsp', isOptional: false },
      { id: 'i5', name: 'Cream', quantity: '0.5', unit: 'cup', isOptional: false },
      { id: 'i6', name: 'Kasuri Methi', quantity: '1', unit: 'tbsp', isOptional: false },
      { id: 'i7', name: 'Garam Masala', quantity: '1', unit: 'tsp', isOptional: false },
    ],
    steps: [
      { id: 's1', stepNumber: 1, instruction: 'Blanch tomatoes and cashews. Blend into smooth paste.', duration: 10 },
      { id: 's2', stepNumber: 2, instruction: 'Heat butter, add paste. Cook until oil separates.', duration: 15 },
      { id: 's3', stepNumber: 3, instruction: 'Add spices — red chili, garam masala, salt, sugar.', duration: 2 },
      { id: 's4', stepNumber: 4, instruction: 'Add cream, mix well. Add paneer cubes.', duration: 5 },
      { id: 's5', stepNumber: 5, instruction: 'Crush kasuri methi and sprinkle. Simmer 5 minutes.', duration: 5, tip: 'Add a pinch of sugar to balance the tomato acidity.' },
    ],
    cookingTime: 35,
    prepTime: 15,
    servings: 4,
    category: 'Dinner' as const,
    cuisine: 'North Indian' as const,
    diet: 'Veg' as const,
    tags: ['creamy', 'rich', 'restaurant-style'],
    images: [],
    coverImage: '/images/paneer-butter-masala.png',
    isFavorite: true,
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 2,
    difficulty: 'Easy' as const,
    calories: 380,
    rating: 4.7,
    viewCount: 189,
  },
  {
    id: 'sample-4',
    title: 'GULAB JAMUN',
    description: 'Golden-fried milk dumplings soaked in rose-cardamom sugar syrup. The ultimate Indian dessert experience.',
    ingredients: [
      { id: 'i1', name: 'Khoya/Mawa', quantity: '200', unit: 'grams', isOptional: false },
      { id: 'i2', name: 'All-Purpose Flour', quantity: '3', unit: 'tbsp', isOptional: false },
      { id: 'i3', name: 'Sugar', quantity: '2', unit: 'cups', isOptional: false },
      { id: 'i4', name: 'Cardamom', quantity: '4', unit: 'pods', isOptional: false },
      { id: 'i5', name: 'Rose Water', quantity: '1', unit: 'tsp', isOptional: true },
      { id: 'i6', name: 'Ghee', quantity: 'for', unit: 'frying', isOptional: false },
    ],
    steps: [
      { id: 's1', stepNumber: 1, instruction: 'Make sugar syrup with water, sugar, cardamom, and rose water. Keep warm.', duration: 15 },
      { id: 's2', stepNumber: 2, instruction: 'Crumble khoya, add flour. Knead into smooth dough using milk.', duration: 10 },
      { id: 's3', stepNumber: 3, instruction: 'Roll into smooth, crack-free balls.', duration: 10, tip: 'If dough cracks, add a few drops of milk.' },
      { id: 's4', stepNumber: 4, instruction: 'Deep fry on LOW heat until deep golden brown all over.', duration: 15, tip: 'Low heat is crucial — high heat will leave them raw inside.' },
      { id: 's5', stepNumber: 5, instruction: 'Soak fried balls in warm syrup for at least 2 hours.', duration: 120 },
    ],
    cookingTime: 60,
    prepTime: 30,
    servings: 20,
    category: 'Dessert' as const,
    cuisine: 'North Indian' as const,
    diet: 'Veg' as const,
    tags: ['sweet', 'festive', 'traditional', 'rich'],
    images: [],
    coverImage: '/images/gulab-jamun.png',
    isFavorite: false,
    createdAt: Date.now() - 86400000,
    updatedAt: Date.now() - 86400000,
    difficulty: 'Medium' as const,
    calories: 150,
    rating: 4.6,
    viewCount: 312,
  },
  {
    id: 'sample-5',
    title: 'DRAGON CHICKEN',
    description: 'Crispy fried chicken tossed in a fiery sweet-sour-spicy Indo-Chinese sauce with bell peppers and spring onions.',
    ingredients: [
      { id: 'i1', name: 'Chicken', quantity: '500', unit: 'grams', isOptional: false },
      { id: 'i2', name: 'Cornflour', quantity: '4', unit: 'tbsp', isOptional: false },
      { id: 'i3', name: 'Soy Sauce', quantity: '2', unit: 'tbsp', isOptional: false },
      { id: 'i4', name: 'Chili Sauce', quantity: '3', unit: 'tbsp', isOptional: false },
      { id: 'i5', name: 'Bell Peppers', quantity: '2', unit: 'medium', isOptional: false },
      { id: 'i6', name: 'Spring Onions', quantity: '4', unit: 'stalks', isOptional: false },
      { id: 'i7', name: 'Garlic', quantity: '8', unit: 'cloves', isOptional: false },
    ],
    steps: [
      { id: 's1', stepNumber: 1, instruction: 'Marinate chicken with cornflour, egg, salt, and pepper.', duration: 30 },
      { id: 's2', stepNumber: 2, instruction: 'Deep fry chicken pieces until golden and crispy.', duration: 15 },
      { id: 's3', stepNumber: 3, instruction: 'In a wok, sauté garlic, ginger, and dried red chilies.', duration: 3 },
      { id: 's4', stepNumber: 4, instruction: 'Add soy sauce, chili sauce, vinegar, and sugar. Cook 2 min.', duration: 3 },
      { id: 's5', stepNumber: 5, instruction: 'Toss in fried chicken, bell peppers, spring onions. Stir-fry high heat.', duration: 5, tip: 'Keep the flame high for that smoky wok flavor.' },
    ],
    cookingTime: 40,
    prepTime: 35,
    servings: 4,
    category: 'Snacks' as const,
    cuisine: 'Chinese' as const,
    diet: 'Non-Veg' as const,
    tags: ['spicy', 'crispy', 'indo-chinese', 'party'],
    images: [],
    coverImage: '/images/dragon-chicken.png',
    isFavorite: true,
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now() - 86400000 * 4,
    difficulty: 'Medium' as const,
    calories: 420,
    rating: 4.5,
    viewCount: 278,
  },
  {
    id: 'sample-6',
    title: 'MANGO LASSI',
    description: 'Creamy, chilled yogurt smoothie blended with ripe Alphonso mangoes, sugar, and a hint of cardamom.',
    ingredients: [
      { id: 'i1', name: 'Mango Pulp', quantity: '1', unit: 'cup', isOptional: false },
      { id: 'i2', name: 'Yogurt', quantity: '1', unit: 'cup', isOptional: false },
      { id: 'i3', name: 'Sugar', quantity: '2', unit: 'tbsp', isOptional: false },
      { id: 'i4', name: 'Cardamom Powder', quantity: '0.25', unit: 'tsp', isOptional: true },
      { id: 'i5', name: 'Ice Cubes', quantity: '4', unit: 'cubes', isOptional: false },
    ],
    steps: [
      { id: 's1', stepNumber: 1, instruction: 'Blend mango pulp, yogurt, sugar, and cardamom until smooth.', duration: 2 },
      { id: 's2', stepNumber: 2, instruction: 'Add ice cubes and blend again for 30 seconds.', duration: 1 },
      { id: 's3', stepNumber: 3, instruction: 'Pour into tall glass. Garnish with saffron strands and pistachios.', duration: 1, tip: 'Use chilled yogurt for the best texture.' },
    ],
    cookingTime: 5,
    prepTime: 5,
    servings: 2,
    category: 'Beverage' as const,
    cuisine: 'North Indian' as const,
    diet: 'Veg' as const,
    tags: ['quick', 'refreshing', 'summer', 'healthy'],
    images: [],
    coverImage: '/images/mango-lassi.png',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    difficulty: 'Easy' as const,
    calories: 180,
    rating: 4.9,
    viewCount: 567,
  },
];
